- hosts: kube-master
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  become: true
  tags:
    - client
  roles:
    - { role: kubespray-defaults}
    - { role: kubernetes/client, vars: {kubectl_localhost: true, kubeconfig_localhost: true} }
  vars_files:
    - roles/kubernetes/client/defaults/main.yml
